version: "3"

services:
  vault:
    image: vault:1.1.2
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -dev -dev-root-token-id="vamp" -dev-listen-address="0.0.0.0:8200"
