version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.1
      - image: circleci/vault-cci
        environment:
          SKIP_SETCAP: skip
    steps:
      - checkout
      - run: |
          VAULT_CLIENT_TOKEN=$(curl localhost:8201/client-token)
          curl --fail -v -X POST -H "X-Vault-Token:${VAULT_CLIENT_TOKEN}" -d '{"type": "kv"}' localhost:8200/v1/sys/mounts/secret
      - run: mkdir -p ./artifacts
      - run: git config --global url.git@github.com:.insteadOf https://github.com/
      - run: ./test.sh
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ./integrationtest.sh circleci
      - run: ./build.sh local
      - run: cp ./bin/* ./artifacts
      - run: cp ./bin/forklift-darwin-amd64 ./artifacts/forklift-darwin-x86_64
      - run: cp ./bin/forklift-linux-amd64 ./artifacts/forklift-linux-x86_64
      - run: go run main.go version clean > ./artifacts/version.txt
      - persist_to_workspace:
          root: ./artifacts
          paths:
            - .
  publish-github-release:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./artifacts/version.txt)
            rm ./artifacts/version.txt
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^(v)\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(v)\d+\.\d+\.\d+$/
