namespace: vampio
database-type: mysql
database-name: vamp-${namespace}
database-url: jdbc:mysql://mysql.default.svc.cluster.local:3306/vamp-${namespace}
database-user: root
database-table: ${namespace}
database-password: secret
key-value-store-url: ${env://VAMP_PERSISTENCE_KEY_VALUE_STORE_VAULT_URL}
key-value-store-token: ${env://VAMP_PERSISTENCE_KEY_VALUE_STORE_VAULT_TOKEN}
key-value-store-base-path: /secret/vamp/${namespace}
key-value-store-type: vault
